"""Initial migration

Revision ID: 9ebfcd112d56
Revises: 
Create Date: 2024-06-09 10:22:57.830616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

def index_exists(index_name, table_name):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
    return index_name in indexes

# revision identifiers, used by Alembic.
revision: str = '9ebfcd112d56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not index_exists('ix_compared_products_confirm_purchase_duplicate_url_name', 'compared_products_confirm_purchase_duplicate'):
        op.create_index(op.f('ix_compared_products_confirm_purchase_duplicate_url_name'), 'compared_products_confirm_purchase_duplicate', ['url_name'], unique=False)
    op.create_unique_constraint(None, 'compared_products_confirm_purchase_duplicate', ['product_id'])
    if not index_exists('ix_compared_products_insta_buy_duplicate_url_name', 'compared_products_insta_buy_duplicate'):
        op.create_index(op.f('ix_compared_products_insta_buy_duplicate_url_name'), 'compared_products_insta_buy_duplicate', ['url_name'], unique=False)
    op.create_unique_constraint(None, 'compared_products_insta_buy_duplicate', ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compared_products_insta_buy_duplicate', type_='unique')
    op.drop_index(op.f('ix_compared_products_insta_buy_duplicate_url_name'), table_name='compared_products_insta_buy_duplicate')
    op.drop_constraint(None, 'compared_products_confirm_purchase_duplicate', type_='unique')
    op.drop_index(op.f('ix_compared_products_confirm_purchase_duplicate_url_name'), table_name='compared_products_confirm_purchase_duplicate')
    # ### end Alembic commands ###
